---
CI: TRUE
PATH:
  LOCAL:
    RAW_DATASET: C:\raw_data\epilepsiae
    RESULTS: C:\Users\noam\Repositories\noamsgl\msc\results
    PSP_DATASET: C:\Users\noam\Repositories\noamsgl\msc\results\epilepsiae
    SEIZURES_DATASET: C:\Users\noam\Repositories\noamsgl\msc\results\epilepsiae

  BGUCLUSTER:
    RAW_DATASET: /cs_storage/noamsi/raw_data/epilepsiae/
    RESULTS: /cs_storage/noamsi/results/
    PSP_DATASET: /cs_storage/noamsi/results/epilepsiae/


  MIRIAM:
    RAW_DATASET: \\132.72.65.115\epilepsy_data\Epilepsiea\raw_data


TASK:
  PICKS: "one_channel"
  RESAMPLE: "256"
  PREICTAL_MIN_DIFF_HOURS: "1"
  INTERICTAL_MIN_DIFF_HOURS: "4"
  INTERICTAL_LABEL: "0"
  PREICTAL_LABEL: "1"
  ICTAL_LABEL: "2"


RESULTS:
  LOCAL:

  BGUCLUSTER:
    RESULTS_DIR: "/cs_storage/noamsi/results"

DATASET: epilepsiae
RAW_MACHINE: MIRIAM
RESULTS_MACHINE: LOCAL
