---
FAST_DEV: FALSE
FAST_DEV_K: 3

dataset_id: I004_A0003_D001
duration: 10
num_channels: 2
INDEX_MACHINE: BGUCLUSTER
RAW_MACHINE: BGUCLUSTER
RESULTS_MACHINE: BGUCLUSTER

TASK:
  RESAMPLE: 256
  PREICTAL_MIN_DIFF_HOURS: 1
  INTERICTAL_MIN_DIFF_HOURS: 4
  INTERICTAL_LABEL: "0"
  PREICTAL_LABEL: "1"
  ICTAL_LABEL: "2"

PATH:
  LOCAL:
    ROOT: C:\Users\noam\Repositories\noamsgl\msc\
    RESULTS: C:\Users\noam\Repositories\noamsgl\msc\results
    IEEG_DATASET: C:\Users\noam\Repositories\noamsgl\msc\results\ieeg
    LIGHTNING_LOGS: C:\Users\noam\Repositories\noamsgl\msc\results\lightning_logs

  BGUCLUSTER:
    ROOT: /cs_storage/noamsi/msc/
    RESULTS: /cs_storage/noamsi/results/
    IEEG_DATASET: /cs_storage/noamsi/msc/results/ieeg
    LIGHTNING_LOGS: /cs_storage/noamsi/msc/results/lightning_logs
